modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/noeppi-noeppi/bongo/issues"
license="Apache-2.0"

[[mods]]
modId="bongo"
version="${file.jarVersion}"
displayName="Bongo"
displayURL="https://www.curseforge.com/minecraft/mc-mods/bongo"
updateJSONURL="https://assets.melanx.de/updates/bongo.json"
authors="noeppi_noeppi"
description='''
It's a bingo mod.
'''

[[dependencies.bongo]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="libx"
    mandatory=true
    versionRange="[1.19.2-4.2.7,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="skyblockbuilder"
    mandatory=false
    versionRange="[1.19.1-4.1.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="minemention"
    mandatory=false
    versionRange="[1.19.1-2.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="jei"
    mandatory=false
    versionRange="[11.2.0.256,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="jade"
    mandatory=false
    versionRange="[8.0.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="broglisowls"
    mandatory=true
    versionRange="[0.0.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="mandragora"
    mandatory=true
    versionRange="[0.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="gardens_of_the_dead"
    mandatory=true
    versionRange="[1.19.2-1.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="villagersoctober"
    mandatory=true
    versionRange="[1.19.2-1.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="halloween_mood"
    mandatory=true
    versionRange="[1.0.9,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="bonezone"
    mandatory=true
    versionRange="[1.0.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="funkyframes"
    mandatory=true
    versionRange="[1.0.0.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="cursedcrypts"
    mandatory=true
    versionRange="[1.1.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="pumpkillagersquest"
    mandatory=true
    versionRange="[2.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="maledicta"
    mandatory=true
    versionRange="[1.19.2-1.0.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="hauntedfields"
    mandatory=true
    versionRange="[1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="kindled"
    mandatory=true
    versionRange="[1.0.1,)"
    ordering="NONE"
    side="BOTH"
